### ISSUE TITLE
Asking about the meaning of dataset data

### ISSUE THREAD

**Issue by WENplay** [lujiaxuan0520/THU-EACT-50#1]
Hello author, thank you for providing the event camera dataset. Recently, I had the opportunity to read your paper "Action Recognition and Benchmark Using Event Cameras". Now, I use this dataset for academic research, but when I open the dataset file, I don't know what each column of data means. The .csv file in THU-EACT-50 has 5 columns, what is the meaning of each column? In the THU-EACT-50-CHL dataset, there are four elements for each list in the .npy file. What is the meaning of each element? I did not find the answer in your paper and Redme.md. In the paper, the format of the event stream is x, y, t, p, I can only find the corresponding part of p. If you could answer my question, I would greatly appreciate it.Thank you.

**Comment by lujiaxuan0520** [comment]
Hello,

Thank you for your interest in our dataset and for taking the time to read our paper. I apologize for the inconvenience and I'd be happy to clarify the format of the data.

In the THU-EACT-50 dataset, which is provided in the .csv format, the data is structured with 5 columns as follows:

1. y: Represents the y-coordinate of the event.
2. x: Represents the x-coordinate of the event.
3. b: This is an additional brightness value provided by the Celex-V camera. It's worth noting that for our method, this value is not utilized.
4. p: The polarity value. It contains three categories: 1, -1, and 0. In our experiments, we ignore the 0 values and consider 1 as positive polarity and -1 as negative polarity.
5. t: Represents the timestamp of the event.

For the THU-EACT-50-CHL dataset, which is available in the .npy format, each list contains 4 elements:

1. x: Represents the x-coordinate of the event.
2. y: Represents the y-coordinate of the event.
3. t: Represents the timestamp of the event.
4. p: The polarity value. In this dataset, the polarity only includes standard values of 1 and 0. Here, 1 represents positive polarity, and 0 represents negative polarity.

I hope this provides clarity on the structure of our datasets. We'll add the above explanation to the Readme file as well.

Best regards

**Comment by WENplay** [comment]
Ok, thank you for your reply.
