### ISSUE TITLE
Ask for code details

### ISSUE THREAD

**Issue by WENplay** [lujiaxuan0520/THU-EACT-50#2]
Hello author,
After reading your paper, I wanted to follow the steps in the paper to process the event flow, but I couldn't find your source code. Would you like to disclose the source code?
I would like to ask, in the process of voxel processing of event streams, x, y, and t are averaged, and how is the polarity p handled? Can you provide a detailed explanation of the processing process?
I would greatly appreciate it if you could reply to these questions.
Thank you.

**Comment by lujiaxuan0520** [comment]
Dear,

At present, the complete source code associated with the paper has not been authorized for open-source release. However, we do not rule out the possibility of making it available in the future.

To facilitate experimentation, we have updated and provided demo codes for dataset loading in `dataset.py` and `process.py`. Please refer to the examples in `dataset.py` for guidance on basic data loading and computation of common intermediate representations.

Regarding the voxel processing of event streams, we perform voxel filtering operations separately for each type of polarities before combining them. Once filtered, the event streams of both polarities are combined to form an intermediate representation.

I hope this clarifies your queries. If you have any more questions or require further assistance, please feel free to ask.

Best regards

**Comment by WENplay** [comment]
Okay, thank you for your answer.
